# Generated by Django 5.1 on 2024-08-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_artist_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='dob',
            field=models.DateField(),
        ),
    ]
